mysql <<EOFMYSQL
use sc133;
show tables;

DROP TABLE INTERVIEWERS;
DROP TABLE APPLICATIONS;
DROP TABLE JOBS;
DROP TABLE STUDENTS;

CREATE TABLE STUDENTS (
STUDENT_ID char(10),
STUDENT_NAME varchar(50) NOT NULL,
MAJOR varchar(50) NOT NULL,
PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE JOBS (
JOB_ID char(10),
COMPANY_NAME varchar(50) NOT NULL,
JOB_TITLE varchar(50) NOT NULL,
SALARY int,
DESIRED_MAJOR varchar(50),
PRIMARY KEY (JOB_ID)
);

CREATE TABLE APPLICATIONS (
STUDENT_ID char(10),
JOB_ID char(10),
PRIMARY KEY (STUDENT_ID, JOB_ID),
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE RESTRICT,
FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE RESTRICT
);

CREATE TABLE INTERVIEWERS (
INTERVIEWER_ID char(10),
INTERVIEWER_NAME varchar(50) NOT NULL,
INTERVIEW_TIME time,
JOB_ID char(10),
PRIMARY KEY (INTERVIEWER_ID),
FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE RESTRICT
);

INSERT INTO STUDENTS VALUES ('01234', 'Sandeep Chitturi','Computer Science');
INSERT INTO STUDENTS VALUES ('56789', 'Luis Guerra', 'Computer Science');
INSERT INTO STUDENTS VALUES ('24680', 'Bob Smith', 'Computer Engineer');

INSERT INTO JOBS VALUES ('00000', 'Microsoft', 'Engineer', '150000', 'Computer Science');
INSERT INTO JOBS VALUES ('11111', 'Sony', 'Manager', '120000', 'Computer Engineer');
INSERT INTO JOBS VALUES ('10101', 'Nintendo', 'Director', '500000', 'Computer Engineer');

INSERT INTO APPLICATIONS VALUES ('24680', '10101');
INSERT INTO APPLICATIONS VALUES ('56789', '11111');

INSERT INTO INTERVIEWERS VALUES ('22222', 'Walter White', '15:00', '10101');
INSERT INTO INTERVIEWERS VALUES ('33333', 'Tony Soprano', '13:30', '11111');

SELECT * FROM STUDENTS;
SELECT * FROM JOBS;
SELECT * FROM APPLICATIONS;
SELECT * FROM INTERVIEWERS;

EOFMYSQL
